conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("sites.urls", namespace="main")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sites/urls.py
from django.urls import path
from . import views

app_name = "sites"

urlpatterns = [
    path("", view= views.idea_list, name="idea_list"),
    path("idea", view= views.idea_list, name="idea_list"),
    path("idea/<int:pk>", view=views.idea_detail, name="idea_detail"),
    path("idea/create", view=views.idea_create, name="idea_create"),
    path("idea/<int:pk>/edit", view=views.idea_edit, name="idea_edit"),
    path("idea/<int:pk>/delete", view=views.idea_delete, name="idea_delete"),

    path("tool", view= views.tool_list, name="tool_list"),
    path("tool/<int:pk>", view=views.tool_detail, name="tool_detail"),
    path("tool/create", view=views.tool_create, name="tool_create"),
    path("tool/<int:pk>/edit", view=views.tool_edit, name="tool_edit"),
    path("tool/<int:pk>/delete", view=views.tool_delete, name="tool_delete"),
]

sites/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import DateTimeField, related
from conf.utils import uuid_upload_to

# Create your models here.

class Tool(models.Model):
    name = models.CharField(max_length=50)
    kind = models.CharField(max_length=50)
    des = models.TextField()

    def __str__(self):
        return self.name

class Idea(models.Model):
    title = models.CharField(max_length=100) 
    image = models.ImageField(upload_to="idea_img/%Y/%m/%d", null=True)
    content = models.TextField()
    interest = models.IntegerField(default=0)
    # Foriegn Key -> 한 Tool에 여러 Idea
    devtool = models.ForeignKey(Tool, on_delete=models.SET_NULL, null=True)
    update_at = models.DateTimeField(auto_now=True) # 이거 꼭 넣어줘야함. 
    create_at = models.DateTimeField(auto_now_add=True)  

sites/forms.py
from django import forms
from . import models

class IdeaForm(forms.ModelForm):
    class Meta:
        model = models.Idea
        fields = '__all__'

class ToolForm(forms.ModelForm):
    class Meta:
        model = models.Tool
        fields = '__all__'
        

sites/views.py
from sites.forms import IdeaForm
from sites.forms import ToolForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls.base import reverse
from .models import Idea
from .models import Tool
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

# ------------------------------- idea -------------------------------

@csrf_exempt
def idea_list(request):
    all_ideas = Idea.objects.all()
    ctx = {
        "all_ideas":all_ideas
    }
    return render(request, template_name="ideas/idea_list.html", context=ctx)

def idea_detail(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    tool_id = idea.devtool.id
    print("___________________________________________" ,tool_id)
    ctx = {
        "idea":idea,
        "tool_id":tool_id,
    }
    return render(request, template_name="ideas/idea_detail.html", context=ctx)

def idea_create(request):
    # 만약 create 페이지에서 create를 누르면
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            idea = form.save()
            return redirect('sites:idea_detail', idea.pk)
    else:
        form = IdeaForm()
        ctx = {
            'form':form
            }
        
        return render(request, template_name="ideas/idea_create.html", context = ctx)

def idea_edit(request,pk):
    idea = get_object_or_404(Idea, id=pk)
    if request.method == "POST":
        form = IdeaForm(request.POST, instance=idea)
        if form.is_valid():
            idea = form.save()
            return redirect('sites:idea_detail', pk)
    else:
        form = IdeaForm(instance=idea)
        ctx = {
            'form':form
            }
        
        return render(request, template_name="ideas/idea_create.html", context = ctx)

def idea_delete(request,pk):
    idea = get_object_or_404(Idea, id=pk)
    idea.delete()
    return redirect('sites:idea_list')


# ------------------------------- tool -------------------------------
def tool_list(request):
    all_tools = Tool.objects.all()
    ctx = {
        "all_tools":all_tools
    }
    return render(request, template_name="tools/tool_list.html", context=ctx)

def tool_detail(request, pk):
    tool = get_object_or_404(Tool, id=pk)
    ideas = Idea.objects.filter(devtool = tool)
    ctx = {
        "tool":tool,
        "ideas":ideas,
    }
    return render(request, template_name="tools/tool_detail.html", context=ctx)

def tool_create(request):
    # 만약 create 페이지에서 create를 누르면
    if request.method == "POST":
        form = ToolForm(request.POST, request.FILES)
        if form.is_valid():
            tool = form.save()
            return redirect('sites:tool_detail', tool.pk)
    else:
        form = ToolForm()
        ctx = {
            'form':form
            }
        
        return render(request, template_name="tools/tool_create.html", context = ctx)

def tool_edit(request,pk):
    tool = get_object_or_404(Tool, id=pk)
    if request.method == "POST":
        form = ToolForm(request.POST, instance=tool)
        if form.is_valid():
            tool = form.save()
            return redirect('sites:tool_detail', pk)
    else:
        form = ToolForm(instance=tool)
        ctx = {
            'form':form
            }
        
        return render(request, template_name="tools/tool_create.html", context = ctx)

def tool_delete(request,pk):
    tool = get_object_or_404(Tool, id=pk)
    tool.delete()
    return redirect('sites:tool_list')

sites/templates/ideas/idea_create.html
{%extends "layout.html"%} 

{% block content %}
    <h1>Idea Register</h1>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>

        <button type="submit" >SUBMIT</button>
    </form>

{% endblock %} 

sites/templates/ideas/idea_detail.html
{%extends "layout.html"%} 
{% block content %}
    <h1>{{ idea.title }}</h1>

    <img src = "{{ idea.image.url }}" height="300">
    <h4> 내용 : {{idea.content}} </h4> 
    <h4> 관심도 : {{ idea.interest }}</h4> 
    
    <h4> 개발 tool : <a href="{% url "sites:tool_detail" tool_id %}">{{ idea.devtool }}</a></h4> 
    <hr/>
    <span><a href="{% url "sites:idea_delete" idea.id %}"> 삭제 </a></span>
    <span><a href="{% url "sites:idea_list" %}"> 목록 </a></span>
    <span><a href="{% url "sites:idea_edit" idea.id %}"> 수정 </a></span>

{% endblock %} 

sites/templates/ideas/idea_list.html
{%extends "layout.html"%} 
{% block content %}
    <h1>Idea List</h1>
    <span> 나의 아이디어를 잊지 말고 기록해보세요!</span>
    <hr/>

    {% for idea in all_ideas %}
        <img src = "{{ idea.image.url }}" height="300">
        <a href="{% url "sites:idea_detail" idea.id %}"><h3>{{ idea.title }}</h3></a>
        <h4> 개발 tool : {{ idea.devtool }}</h4>
        <h4> 관심도 : <p id="interest-{{idea.id}}">{{ idea.interest }}</p></h4>
        <button id="up-{{idea.id}}"  class = "btn-up" onclick="up( {{idea.id}} )" name={{idea.id}}> ▲ </button>
        <button id="down-{{idea.id}}" class = "btn-down" onclick="down( {{idea.id}} )" name={{idea.id}}> ▼ </button>
        <hr/>
    {% endfor %}
{% endblock %} 

{% block js %}
<script>
    // function으로 해야 모드 list에 버튼 누르기가 적용됨.. event listener는 불가
    function up(num){
        console.log("getin");
        console.log(num);
        //let num = this.target.getAttribute('name');
        let str = "#interest-"+num;
        
        $.ajax({
            type: "POST",
            url: "/idea", 
            contentType: "application/json",
            data: {
                "csrfmiddlewaretoken": "{{ csrf_token }}",
                'num' : num,
                "str":str,
            }, 
            success: function(data){
                let change = document.querySelector(str);
                let current = parseInt(change.textContent, 10);
                change.textContent = current + 1;
                
            },
            error: function(){
                alert('실패 ㅅㄱ')
            }
        })
    }

    function down(num){
        console.log("getin");
        console.log(num);
        //let num = this.target.getAttribute('name');
        let str = "#interest-"+num;
        
        $.ajax({
            type: "POST",
            url: "/idea", 
            contentType: "application/json",
            data: {
                "csrfmiddlewaretoken": "{{ csrf_token }}",
                'num' : num,
                "str":str,
            }, 
            success: function(data){
                let change = document.querySelector(str);
                let current = parseInt(change.textContent, 10);
                change.textContent = current - 1;
                
            },
            error: function(){
                alert('실패 ㅅㄱ')
            }
        })
    }

</script>

{% endblock %}

sites/templates/tools/tool_create.html
{%extends "layout.html"%} 

{% block content %}
    <h1>Tool Register</h1>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>

        <button type="submit" >SUBMIT</button>
    </form>

{% endblock %} 

sites/templates/tools/tool_detail.html
{%extends "layout.html"%} 

{% block content %}
    <h1>{{ tool.name }}</h1>

    <h4> 종류 :  {{ tool.kind }}</h4>
    <h4> 설명 :  {{ tool.des }}</h4>
    <h3>만들 수 있는 SW 목록</h3>
    <ul>
        {% for idea in ideas %}
            <li><a href="{% url "sites:idea_detail" idea.id %}"> {{idea.title}} </a></li>
        {% endfor %}
    </ul>
    <hr/>
    <span><a href="{% url "sites:tool_delete" tool.id %}"> 삭제 </a></span>
    <span><a href="{% url "sites:tool_list" %}"> 목록 </a></span>
    <span><a href="{% url "sites:tool_edit" tool.id %}"> 수정 </a></span>

{% endblock %} 

sites/templates/tools/tool_list.html
{%extends "layout.html"%} 
{% block content %}
    <h1>Tool List</h1>
    {% for tool in all_tools %}
        <a href="{% url "sites:tool_detail" tool.id %}"><h3>{{ tool.name }}</h3></a>
        <h4> 종류 :  {{ tool.kind }}</h4>
        <h4> 설명 :  {{ tool.des }}</h4>
        <hr/>
    {% endfor %}
{% endblock %} 

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>SWIDEA_SITE</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
    My SW Idea Manage
    
    <ul>
        <li><a href= "{% url "sites:idea_create" %}">아이디어 등록</a></li>
        <li><a href= "{% url "sites:idea_list" %}">아이디어 관리</a></li>
        <li><a href= "{% url "sites:tool_create" %}">개발툴 등록</a></li>
        <li><a href= "{% url "sites:tool_list" %}">개발툴 관리</a></li>
    </ul>

    {% block content %}
    {% endblock %}
</body>
    {% block js %}
    {% endblock %}
</html> 